// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-OM2JCQhiQHo7qaPyj7TEcyxtETUVeU',
    appId: '1:809872088086:web:cf55e86b0cd1460b586937',
    messagingSenderId: '809872088086',
    projectId: 'doan2-e8e0f',
    authDomain: 'doan2-e8e0f.firebaseapp.com',
    storageBucket: 'doan2-e8e0f.firebasestorage.app',
    measurementId: 'G-ELV2GHHLL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-vTgetzMIWGl0d035V7M412K1Z9vRqRA',
    appId: '1:809872088086:android:73ee0764bb51cfbd586937',
    messagingSenderId: '809872088086',
    projectId: 'doan2-e8e0f',
    storageBucket: 'doan2-e8e0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdHDgfdVgH6BO86cGtOkYdy5gHlWoJ0S8',
    appId: '1:809872088086:ios:bffc734e4cee499c586937',
    messagingSenderId: '809872088086',
    projectId: 'doan2-e8e0f',
    storageBucket: 'doan2-e8e0f.firebasestorage.app',
    iosBundleId: 'com.example.doan2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL-OM2JCQhiQHo7qaPyj7TEcyxtETUVeU',
    appId: '1:809872088086:web:4252b0e49bed88af586937',
    messagingSenderId: '809872088086',
    projectId: 'doan2-e8e0f',
    authDomain: 'doan2-e8e0f.firebaseapp.com',
    storageBucket: 'doan2-e8e0f.firebasestorage.app',
    measurementId: 'G-16WR727J5S',
  );
}
